name: Release

on:
  pull_request:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: CompeyDev/setup-rokit@v0.1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get model file name
        run: |
          name=$(jq -r .name default.project.json)
          echo "MODEL_FILE=$name.rbxm" >> $GITHUB_ENV

      - name: Install packages
        run: lune run install

      - name: Build
        run: lune run build -- --target prod --output ${{ env.MODEL_FILE }}

      - name: Login to Wally registry
        run: wally login --token ${{ secrets.WALLY_REGISTRY_TOKEN }}

      - name: Publish to Wally
        if: ${{ github.event.release }}
        run: wally publish

      - uses: softprops/action-gh-release@v1
        if: ${{ github.event.release }}
        with:
          files: ${{ env.MODEL_FILE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
